server:
  port: 8081

spring:
  application:
    name: db-connect
  datasource:
    url: 'jdbc:postgresql://localhost:5432/dvdrental'
    username: postgres
    password: admin1914
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'